apiVersion: v1
kind: Secret
metadata:
  name: consumer-secret
  namespace: default
type: Opaque
stringData:
  consumer.properties: |
    host=pq-pubsubplus.solace.svc.cluster.local:55554
    vpn_name=default
    username=YOUR_MSG_USER
    password=YOUR_MSG_USER_PASSWORD
    queue.name=partitioned-queue-2
    # Approximate (max) consumption rate per second
    consume.msg.rate=15
