---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name:      pq-scaled-object
  namespace: default
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          solace-consumer
  pollingInterval:  5
  cooldownPeriod:  60
  minReplicaCount:  1
  maxReplicaCount:  12
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60
          policies:
          - type:          Pods
            value:         1
            periodSeconds: 30
          # - type:          Percent
          #   value:         20
          #   periodSeconds: 30
          selectPolicy:    Min
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type:          Pods
            value:         2
            periodSeconds: 30
          # - type:          Percent
          #   value:         100
          #   periodSeconds: 30
          selectPolicy:    Max
  triggers:
  - type: solace-event-queue
    metadata:
      solaceSempBaseURL:        http://pq-pubsubplus.solace.svc.cluster.local:8080
      messageVpn:               default
      queueName:                partitioned-queue-1
      messageCountTarget:       '50'
      messageReceiveRateTarget: '8'
#      messageSpoolUsageTarget:  '100000'
    authenticationRef:
      name: pq-trigger-auth
