apiVersion: v1
kind: Secret
metadata:
  name:      pq-scaler-secret
  namespace: default
  labels:
    app: solace-consumer
type: Opaque
data:
  SEMP_USER:         YWRtaW4=
  SEMP_PASSWORD:     ZGVtb3Bhc3M=
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pq-trigger-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter:   username
      name:        pq-scaler-secret
      key:         SEMP_USER
    - parameter:   password
      name:        pq-scaler-secret
      key:         SEMP_PASSWORD
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name:      pq-scaled-object
  namespace: default
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          solace-consumer
  pollingInterval:  2
  cooldownPeriod:  60
  minReplicaCount:  2
  maxReplicaCount:  12
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 20
          policies:
          - type:          Pods
            value:         1
            periodSeconds: 60
          selectPolicy:    Min
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type:          Pods
            value:         4
            periodSeconds: 25
          selectPolicy:    Max
  triggers:
  - type: solace-event-queue
    metadata:
      solaceSempBaseURL:       http://pq-pubsubplus.solace.svc.cluster.local:8080
      messageVpn:              default
      queueName:               partitioned-queue-1
      messageCountTarget:      '50'
      messageSpoolUsageTarget: '100000'
    authenticationRef:
      name: pq-trigger-auth