apiVersion: v1
kind: Secret
metadata:
  name: publisher-secret
  namespace: default
type: Opaque
stringData:
  publisher.properties: |
    solace.messaging.transport.host=pq-pubsubplus.solace.svc.cluster.local:55554
    solace.messaging.service.vpn-name=default
    solace.messaging.authentication.basic.username=YOUR_MSG_USER
    solace.messaging.authentication.basic.password=YOUR_MSG_USER_PASSWORD
    solace.messaging.transport.reconnection-attempts=20
    solace.messaging.transport.connection.retries-per-host=5
    topic.prefix=pqdemo
    use.random.key=false
    ## Ignored if random.key == true:
    number.of.unique.keys=20
