---
apiVersion: v1
kind: Secret
metadata:
  name:      pq-scaler-secret
  namespace: default
  labels:
    app: solace-consumer
type: Opaque
data:
  SEMP_USER:         YWRtaW4=
  SEMP_PASSWORD:     ZGVtb3Bhc3M=
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pq-trigger-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter:   username
      name:        pq-scaler-secret
      key:         SEMP_USER
    - parameter:   password
      name:        pq-scaler-secret
      key:         SEMP_PASSWORD
