---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solace-consumer
  namespace: default
spec:
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      volumes:
      - name: consumer-config-file
        secret:
          secretName: consumer-secret
      containers:
      - name: solace-consumer-1
        image: solace-transacted-consumer:latest
        resources:
          limits:
            cpu: "125m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
          - mountPath: /opt/partitioned-queue-demo/config
            name: consumer-config-file
            readOnly: true
        imagePullPolicy: Never
      restartPolicy: Always
