---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name:      pq-scaled-object
  namespace: default
spec:
  scaleTargetRef:
    apiVersion:    apps/v1
    kind:          Deployment
    name:          solace-consumer
  pollingInterval:  3
  cooldownPeriod:  60
  minReplicaCount:  1
  maxReplicaCount:  6
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
          - type:          Pods
            value:         1
            periodSeconds: 30
          selectPolicy:    Min
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type:          Pods
            value:         2
            periodSeconds: 30
          selectPolicy:    Max
  triggers:
  - type: solace-event-queue
    metadata:
      solaceSempBaseURL:        http://pq-pubsubplus.solace.svc.cluster.local:8080
      messageVpn:               default
      queueName:                partitioned-queue-2
      messageCountTarget:       '100'
      messageReceiveRateTarget: '20'
    authenticationRef:
      name: pq-trigger-auth
